name: CI - E2E Mobile Tests

on:
  push:
env:
  EMULATOR_NAME: Pixel
  EMULATOR_DEVICE: Pixel 4
  API_LEVEL: 36
  EMULATOR_VERSION: 12
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  ANDROID_BUILD_TOOLS_VERSION: 34.0.0
  ANDROID_SDK_PACKAGES: system-images;android-32;google_apis;x86_64 platforms;android-32 build-tools;34.0.0-rc4 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  BOOT_TIMEOUT: 700
jobs:
  appium-run:
    runs-on: "macos-13"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - name: "Setup Node.js"
        uses: "actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af"
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm install
      - name: Add avdmanager and sdkmanager to system PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
      - name: print ANDROID_HOME
        run: |
          echo "$ANDROID_HOME"
      - name: print sdkmanager in LOCAL
        run: |
          ls $ANDROID_HOME/build-tools/
      - name: print sdkmanager list
        run: |
          sdkmanager --list
      - name: Install Sdk
        run: |
          yes Y | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}
      - name: Build emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --device "$EMULATOR_DEVICE" --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
      - name: Launch emulator
        run: |
          chmod +x ./sscript/start_emu.sh
          ./sscript/start_emu.sh
      - name: Check emulator booting status
        run: |
          chmod a+x ./sscript/check_emu.sh
          ./sscript/check_emu.sh
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium &
          sleep 10
      - name: "Run tests"
        run: npx wdio
